name: pfe
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.6
  image_picker: ^1.0.7
  path: ^1.8.3
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  fl_chart: ^0.66.1
  percent_indicator: ^4.2.2

  animate_do: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/halva.jpeg
    - assets/images/powerboom.jpeg
    - assets/images/background.jpg
    - assets/images/logo.png
    - assets/images/auth.png
    - assets/images/auth1.png
    - assets/images/auth2.png
    - assets/images/ballon.png
    - assets/images/moulin.png
    - assets/images/reflexx.png
    - assets/images/florida.png 
    - assets/images/home.png 